<?xml version="1.0" encoding="utf-8"?>
<Database Name="helloapp" Class="HelloRepoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IS-MATTLTEST.TESTNET\SQL2008;Initial Catalog=helloapp;Integrated Security=True" SettingsObjectName="Hello.Repo.Properties.Settings" SettingsPropertyName="helloappConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Campaigns" Member="Campaigns">
    <Type Name="Campaign">
      <Column Name="CampaignID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Campaign_Token" Member="Tokens" ThisKey="CampaignID" OtherKey="CampaignID" Type="Token" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Start" Type="System.DateTime" DbType="DATETIME NOT NULL" CanBeNull="false" />
      <Column Name="End" Type="System.DateTime" DbType="DATETIME NOT NULL" CanBeNull="false" />
      <Column Name="HiFiveLimit" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="false" />
      <Association Name="Event_Session" Member="Sessions" ThisKey="EventID" OtherKey="EventID" Type="Session" />
      <Association Name="Event_UserType" Member="UserTypes" ThisKey="EventID" OtherKey="EventID" Type="UserType" />
      <Association Name="Event_HiFive" Member="HiFives" ThisKey="EventID" OtherKey="EventID" Type="HiFive" />
      <Association Name="Event_Seat" Member="Seats" ThisKey="EventID" OtherKey="EventID" Type="Seat" />
    </Type>
  </Table>
  <Table Name="dbo.Friendships" Member="Friendships">
    <Type Name="Friendship">
      <Column Name="Befriender" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Befriendee" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_Friendship" Member="User" ThisKey="Befriendee" OtherKey="Username" Type="User" IsForeignKey="true" />
      <Association Name="User_Friendship1" Member="User1" ThisKey="Befriender" OtherKey="Username" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Points" Member="Points">
    <Type Name="Point">
      <Column Name="PointID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Issued" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="User_Point" Member="User" ThisKey="Username" OtherKey="Username" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Redemptions" Member="Redemptions">
    <Type Name="Redemption">
      <Column Name="RedemptionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TokenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Redemption" Member="User" ThisKey="Username" OtherKey="Username" Type="User" IsForeignKey="true" />
      <Association Name="Token_Redemption" Member="Token" ThisKey="TokenID" OtherKey="TokenID" Type="Token" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TagAggregates" Member="TagAggregates">
    <Type Name="TagAggregate">
      <Column Name="TagAggregateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserTypeID" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(140) NOT NULL" CanBeNull="false" />
      <Column Name="Offensive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Message" Member="User" ThisKey="Username" OtherKey="Username" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Tag" Member="User" ThisKey="Username" OtherKey="Username" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QueuedTweets" Member="QueuedTweets">
    <Type Name="QueuedTweet">
      <Column Name="QueuedTweetID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(140) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Processed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ImageURL" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TideMarks" Member="TideMarks">
    <Type Name="TideMark">
      <Column Name="TideMarkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User" Id="ID1">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ImageURL" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserTypeID" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="ShadowAccount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Friendship" Member="Befriendees" Storage="_Friendships" ThisKey="Username" OtherKey="Befriendee" Type="Friendship" />
      <Association Name="User_Friendship1" Member="Befrienders" Storage="_Friendships1" ThisKey="Username" OtherKey="Befriender" Type="Friendship" />
      <Association Name="User_Point" Member="Points" ThisKey="Username" OtherKey="Username" Type="Point" />
      <Association Name="User_Redemption" Member="Redemptions" ThisKey="Username" OtherKey="Username" Type="Redemption" />
      <Association Name="User_Message" Member="Message" ThisKey="Username" OtherKey="Username" Type="Message" Cardinality="One" />
      <Association Name="User_Tag" Member="Tags" ThisKey="Username" OtherKey="Username" Type="Tag" />
      <Association Name="User_Sat" Member="Sats" ThisKey="Username" OtherKey="Username" Type="Sat" />
      <Association Name="User_HiFive" Member="HiFivers" Storage="_HiFives" ThisKey="Username" OtherKey="HiFiver" Type="HiFive" />
      <Association Name="User_HiFive1" Member="HiFivees" Storage="_HiFives1" ThisKey="Username" OtherKey="HiFivee" Type="HiFive" />
      <Association Name="UserType_User" Member="UserType" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="UserType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sats" Member="Sats">
    <Type Name="Sat">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SessionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SeatID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Sat" Member="User" ThisKey="Username" OtherKey="Username" Type="User" IsForeignKey="true" />
      <Association Name="Session_Sat" Member="Session" ThisKey="SessionID" OtherKey="SessionID" Type="Session" IsForeignKey="true" />
      <Association Name="Seat_Sat" Member="Seat" ThisKey="SeatID" OtherKey="SeatID" Type="Seat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sessions" Member="Sessions">
    <Type Name="Session">
      <Column Name="SessionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Finish" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Session_Sat" Member="Sats" ThisKey="SessionID" OtherKey="SessionID" Type="Sat" />
      <Association Name="Event_Session" Member="Event" ThisKey="EventID" OtherKey="EventID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserTypes" Member="UserTypes">
    <Type Name="UserType">
      <Column Name="UserTypeID" Type="System.String" DbType="Char(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ordering" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefaultColour" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="BurningColour" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="HotColour" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="WarmColour" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="UserType_User" Member="Users" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="User" />
      <Association Name="Event_UserType" Member="Event" ThisKey="EventID" OtherKey="EventID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HiFives" Member="HiFives">
    <Type Name="HiFive">
      <Column Name="HiFiveID" Type="System.Int32" DbType="INT NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HiFiver" Type="System.String" DbType="VARCHAR(50) NOT NULL" CanBeNull="false" />
      <Column Name="HiFivee" Type="System.String" DbType="VARCHAR(50) NOT NULL" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="false" />
      <Association Name="User_HiFive" Member="HiFiverUser" ThisKey="HiFiver" OtherKey="Username" Type="User" IsForeignKey="true" />
      <Association Name="User_HiFive1" Member="HiFiveeUser" ThisKey="HiFivee" OtherKey="Username" Type="User" IsForeignKey="true" />
      <Association Name="Event_HiFive" Member="Event" ThisKey="EventID" OtherKey="EventID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tokens" Member="Tokens">
    <Type Name="Token">
      <Column Name="TokenID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CampaignID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AllowedRedemptions" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Token_Redemption" Member="Redemptions" ThisKey="TokenID" OtherKey="TokenID" Type="Redemption" />
      <Association Name="Campaign_Token" Member="Campaign" ThisKey="CampaignID" OtherKey="CampaignID" Type="Campaign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seats" Member="Seats">
    <Type Name="Seat">
      <Column Name="SeatID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Column]" Member="Column" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="Seat_Sat" Member="Sats" ThisKey="SeatID" OtherKey="SeatID" Type="Sat" />
      <Association Name="Event_Seat" Member="Event" ThisKey="EventID" OtherKey="EventID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SearchUsers" Method="SearchUsers">
    <Parameter Name="SearchString" Parameter="searchString" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="MaxResults" Parameter="maxResults" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>